### PR TITLE
Just some cleaning: trailing spaces, lines to long, etc.

### PR DESCRIPTION
**Pull request by pcaro**
Just some code clean

### CODE REVIEW

**Comment by FrancisUsher** [comment]
Any thoughts about adding a pylint config to standardize code style?

**Comment by jeroen94704** [comment]
> 
> 
> Just some code clean

Awesome, thanks for your contribution. Approved.

**Comment by jeroen94704** [comment]
> 
> 
> Any thoughts about adding a pylint config to standardize code style?

Linters are always a good thing IMHO. I'm not normally a python person, so no experience with pylint. Do you have any pointers?

**Comment by pcaro** [comment]
> > Any thoughts about adding a pylint config to standardize code style?
> 
> Linters are always a good thing IMHO. I'm not normally a python person, so no experience with pylint. Do you have any pointers?

pylint and black are the most common.

**Comment by pcaro** [comment]
> Any thoughts about adding a pylint config to standardize code style?

I prefer black (nothing to configurate for a little project and looks like very well):

Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

**Pull request merged**
